# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.1.5-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4

    working_directory: ~/dreamsgem

    steps:
      - run:
          name: Install dependencies
          working_directory: ~/
          command: |
            sudo apt-get -y -qq update
            sudo apt-get -y -qq install python3.4-dev zip
            curl -O https://bootstrap.pypa.io/get-pip.py
            python3.4 get-pip.py --user
            ~/.local/bin/pip install awscli --upgrade --user
      - checkout
      - run:
          name: Deploy
          working_directory: ~/
          command: |
            ts=`date +%s`
            fn="$EB_APP_NAME-$ts.zip"
            find ./dreamsgem -path '*/node_modules/*' -prune -o -path '*/\.git*' -prune -o -type f -print | zip $fn -@
            awscli s3 cp $fn "s3://$S3_BUCKET/$EB_APP_NAME"

            echo "Creating ElasticBeanstalk Application Version ..."
            awscli elasticbeanstalk create-application-version \
              --application-name $EB_APP_NAME-$CIRCLE_BRANCH \
              --version-label "$EB_APP_NAME-$ts" \
              --description "$EB_APP_NAME-$ts" \
              --source-bundle S3Bucket="$S3_BUCKET",S3Key="$EB_APP_NAME" --auto-create-application
